### ISSUE TITLE
Improving the Contributing Guide

### ISSUE THREAD

**Issue by phillcoxon** [enspiral/handbook#10]
I find the contributing guide confusing at the moment. 

(1) For those familiar and already using git wouldn't it be better to suggest they clone enspiral/handbook and submit pull requests directly back to the main repo rather than their own fork?

(2) For people who are less familiar with git I get asking them to fork the repo so they can edit directly on github or using prose.io/#username/handbook.  However it doesn't address keeping their forked copy up to date with changes happening on enspiral/handbook. 

Can we update the guide with instructions on how they can periodically sync new changes from enspiral/handbook to their forked copy?

**Comment by rdbartlett** [comment]
Sorry I didn't see this earlier Phill. I've just updated the Contributing guidelines. Feel free to open a new issue if you think it needs more changes beyond that :)
